
save_result: True
BATCH_SIZE: 1
NUM_WORKERS: 1

simulation_parameters:
  network: easyCNN_02
  model: Trained/easyCNN_02.pth
  base_dir: ''
  dataset: '../easy2VERIFY_Dataset/9dccad39-327a-4ffa-b5d4-04491915f0e2'
  use_metadata: False
  