
save_result: True
BATCH_SIZE: 1
NUM_WORKERS: 1

simulation_parameters:
  network: easyCNN_04
  model: Trained/easyCNN_04.pth
  base_dir: ''
  dataset: '../easy2VERIFY_Dataset/03d59f9d-fe80-4e86-b29c-ec015c9619a2'
  use_metadata: False
  