
is_training: True
is_continuing: False

BATCH_SIZE: 16
NUM_WORKERS: 24
EPOCHS: 100
LEARNING_RATE: 0.0001
RATIO: 0.8

training_parameters:
  seed: 42
  network: easyCNN
  model: 'easyCNN_01.pth'
  dataset: '../easy2VERIFY_Dataset/'