
save_result: True
BATCH_SIZE: 1
NUM_WORKERS: 1

simulation_parameters:
  network: easyCNN_04
  model: Trained/easyCNN_04.pth
  base_dir: ''
  dataset: '../easy2VERIFY_Dataset/5564a422-2129-406d-bad4-470197ce8fcc'
  use_metadata: False
  